
server:
  port: 8011
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    #publisher-confirms: true
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true


#  redis:
#    #host: 129.204.207.127
#    database: 6 # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
#    host: 127.0.0.1
#    port: 6379
#    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
#    max-idle: 20     # 连接池中的最大空闲连接
#    min-idle: 0     # 连接池中的最小空闲连接
#    timeout: 10000   # 连接超时
#    #password: 123456 # 密码,默认密码为空
#    #cluster:       # 集群配置
#    #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
#    #max-redirects: 2  # 最大重定向次数

#  datasource:
#    username: root
#    password: 7890
#    url中database为对应的数据库名称
#    url: jdbc:mysql://localhost:3306/pmp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver

